projects/alit/alit/urls.py
from django.urls import path

from . import views

app_name = "alit"

urlpatterns = [
    path('', views.base, name='base'),
    
    path('questionlist/', views.Question_index, name='questionlist'),
    path('<int:question_id>/', views.Question_detail, name='questiondetail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),

    path('algolist/', views.Algoindex, name='algolist'),
    path('algo/<int:algo_id>/', views.Algodetail, name='algodetail'),
    path('algo/create/', views.algo_create, name='algo_create'),
    path('comment/create/algo/<int:algo_id>/', views.comment_create, name='comment_create'),

]

projects/alit/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='index.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),    
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    
]

projects/alit/config/urls.py
from django.contrib import admin
from django.urls import path, include
from alit import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('alit/', include('alit.urls')),
    path('common/', include('common.urls')),
    
]

projects/alit/templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- alit CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>A-lit</title>
        
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Favicons -->
        <link href="{% static 'img/favicon2.png'%}" rel="icon">
        <link href="{% static 'img/favicon2.png'%}" rel="apple-touch-icon">

        <!-- Bootstrap CSS File -->
        <link href="{% static '/lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

        <!-- Libraries CSS Files -->
        <link href="{% static '/lib/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
        <link href="{% static '/lib/animate/animate.min.css'%}" rel="stylesheet">
        <link href="{% static '/lib/ionicons/css/ionicons.min.css'%}" rel="stylesheet">
        <link href="{% static '/lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">
        <link href="{% static '/lib/lightbox/css/lightbox.min.css'%}" rel="stylesheet">

        <!-- Main Stylesheet File -->
        <link href="{% static 'style.css' %}" rel="stylesheet">
        <!-- login style file -->
        <link href=" {% static 'login.css'%} " rel="stylesheet">
        <!-- =======================================================
            Theme Name: DevFolio
            Theme URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
            Author: BootstrapMade.com
            License: https://bootstrapmade.com/license/
        ======================================================= -->

    </head>
    <body>
        {% include "navbar.html" %}
        
        {% block content %}

        {% endblock %}
        {% include "common/login.html"%}
        <!-- jQuery JS -->
        <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
        <!-- Bootstrap JS -->
        <script src="{% static 'bootstrap.min.js' %}"></script>
        <a href="#" class="back-to-top"><i class="fa fa-chevron-up"></i></a>
        <div id="preloader"></div>

        <!-- JavaScript Libraries -->
        <script src="{% static 'lib/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'lib/jquery/jquery-migrate.min.js' %}"></script>
        <script src="{% static 'lib/popper/popper.min.js' %}"></script>
        <script src="{% static 'lib/bootstrap/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'lib/easing/easing.min.js' %}"></script>
        <script src="{% static 'lib/counterup/jquery.waypoints.min.js' %}"></script>
        <script src="{% static 'lib/counterup/jquery.counterup.js' %}"></script>
        <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'lib/lightbox/js/lightbox.min.js' %}"></script>
        <script src="{% static 'lib/typed/typed.min.js' %}"></script>
        <!-- Contact Form JavaScript File -->
        <script src="{% static 'contactform/contactform.js' %}"></script>

        <!-- Template Main Javascript File -->
        <script src="{% static 'js/main.js' %}"></script>
    </body>
</html>

projects/alit/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

projects/alit/templates/navbar.html
{% load static %}
<!--/ Nav Star /-->
  <nav class="navbar navbar-b navbar-trans navbar-expand-md fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'alit:base' %}">A-lit</a>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarDefault"
        aria-controls="navbarDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span></span>
        <span></span>
        <span></span>
      </button>
      <div class="navbar-collapse collapse justify-content-end" id="navbarDefault">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'alit:algolist' %}">algorithm</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'alit:questionlist' %}">Q&A</a>
          </li>
          {% comment %} <li class="nav-item">
            <a class="nav-link" href="#service">Services</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#work">Work</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#contact">Contact</a>
          </li> {% endcomment %}
          <li class="nav-item">
          {% if user.is_authenticated %}
          {% comment %} {% url 'common:profile' %} {% endcomment %}
            <a class="nav-link" href="#">{{ user.userID }}</a>
            <li><a class="nav-link" href="{% url 'common:logout' %}">Logout</a></li>
          {% else %}
            <a class="nav-link" onclick="document.getElementById('id01').style.display='block'">Log in</a>
          {% endif %}
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <!--/ Nav End /-->