projects/alit/alit/urls.py
from django.urls import path

from . import views

app_name = "alit"

urlpatterns = [
    path('', views.base, name='base'),
    
    path('questionlist/', views.Question_index, name='questionlist'),
    path('<int:question_id>/', views.Question_detail, name='questiondetail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),

    path('algolist/', views.Algoindex, name='algolist'),
    path('algo/<int:algo_id>/', views.Algodetail, name='algodetail'),
    path('algo/create/', views.algo_create, name='algo_create'),
    path('comment/create/algo/<int:algo_id>/', views.comment_create, name='comment_create'),

]

projects/alit/config/urls.py
from django.contrib import admin
from django.urls import path, include
from alit import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('alit/', include('alit.urls')),
    path('common/', include('common.urls')),
    
]

projects/alit/alit/models.py
from django.db import models
from common.models import User

# Create your models here.
class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    # on_delete=models.CASCADE : 계정이 삭제되면 계정과 연결된 Question 모델 데이터를 모두 삭제하는 의미
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.subject

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

class Algoset(models.Model):
    title = models.CharField(max_length=200)
    create_date = models.DateTimeField()
    body = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Comment(models.Model):
    algoset = models.ForeignKey(Algoset, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)

projects/alit/alit/forms.py
from django import forms
from alit.models import Question, Answer, Algoset, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels = {
            'subject': '제목',
            'content': '내용',
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변내용'
        }

class AlgoForm(forms.ModelForm):
    class Meta:
        model = Algoset
        fields = ['title', 'body']
        labels = {
            'title': '제목',
            'body': '내용',
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content' : '댓글'  
        }

projects/alit/alit/views.py
from django.shortcuts import render

from django.http import HttpResponse
from .models import Question, Answer, Algoset, Comment
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .forms import QuestionForm, AnswerForm, CommentForm, AlgoForm
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required

def base(request):
    """홈 화면 출력"""
    return render(request, 'index.html')

def Question_index(request):
    """
    질문 목록 출력
    """
    page = request.GET.get('page', '1')

    question_list = Question.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(question_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj}
    return render(request, 'alit/question_list.html', context)

def Question_detail(request, question_id):
    """
    질문 내용 출력
    """
    question = get_object_or_404(Question, id=question_id)
    context = {"question": question}
    return render(request, 'alit/question_detail.html', context)

# '애너테이션' 이라고 함
# @login_required 애너테이션을 통해 로그인이 되었는지를 우선 검사함
@login_required(login_url='common:login')
def answer_create(request, question_id):
    """ alit 답변등록"""
    question = get_object_or_404(Question, id=question_id)
    
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('alit:questiondetail', question_id = question.id)
    else:
        form = AnswerForm()
    context = {'question' : question, 'form' : form}
    return render(request, 'alit/question_detail.html', context)

@login_required(login_url='common:login')
def question_create(request):
    """ alit 질문등록"""
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('alit:questionlist')
    else:
        form = QuestionForm()

    context = {'form' : form}
    return render(request, 'alit/question_form.html', context)

def Algoindex(request):
    page = request.GET.get('page', '1')

    algo_list = Algoset.objects.order_by('-create_date')

    # 페이징처리
    paginator = Paginator(algo_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'algo_list': page_obj}
    return render(request, 'alit/algo_list.html', context)

@login_required(login_url='common:login')
def algo_create(request):
    """ alit 질문등록"""
    if request.method == 'POST':
        form = AlgoForm(request.POST)
        if form.is_valid():
            algoset = form.save(commit=False)
            algoset.author = request.user
            algoset.create_date = timezone.now()
            algoset.save()
            return redirect('alit:algolist')
    else:
        form = AlgoForm()

    context = {'form' : form}
    return render(request, 'alit/algo_form.html', context)

def Algodetail(request, algo_id):
    """
    algo 내용 출력
    """
    algo = get_object_or_404(Algoset, id=algo_id)
    context = {"algo": algo}
    return render(request, 'alit/algo_detail.html', context)

@login_required(login_url='common:login')
def comment_create(request, algo_id):
    """ alit 답변등록"""
    algo = get_object_or_404(Algoset, id=algo_id)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.algoset = algo
            comment.save()
            return redirect('alit:algodetail', algo_id=algo.id)
    else:
        form = CommentForm()
    context = {'algo' : algo, 'form' : form}
    return render(request, 'alit/algo_detail.html', context)

projects/alit/templates/alit/algo_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ algo.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ algo.body }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ algo.author.userID }}</div>
                    <div>{{ algo.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{algo.comment_set.count}}개의 댓글이 있습니다.</h5>
    {% for comment in algo.comment_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ comment.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ comment.author.userID }}</div>
                    <div>{{ comment.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'alit:comment_create' algo.id %}" method="post" class="my-3">
        {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
                </div>
            {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        {% if user.is_authenticated %}
        <input type="submit" value="댓글등록" class="btn btn-primary">
        {% endif %}
    </form>
</div>
{% endblock %}

projects/alit/templates/alit/algo_form.html
{% extends 'index.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">강의 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        
        <div class="form-group">
            <label for="title">제목</label>
            <input type="text" class="form-control" name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="body">내용</label>
            <textarea class="form-control" name="body"
                      id="body" rows="10">{{ form.body.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

projects/alit/templates/alit/algo_list.html
{% extends 'base.html' %}
{% load static %}
{% load alit_filter %}
{% block content %}
 {% comment %} class="intro route bg-image" style="background-image: url({% static 'img/Rotterdam_street.jpg' %})" {% endcomment %}
<div>
    <div class="container my-3">
        <table class="table">
            <thead>
            <tr class="thead-dark text-center">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if algo_list %}
                {% for algo in algo_list %}
                <tr class="text-center">
                    <td>{{ algo_list.paginator.count|sub:algo_list.start_index|sub:forloop.counter0|add:1 }}</td>
                    <td class="text-left">
                        <a href="{% url 'alit:algodetail' algo.id %}">{{ algo.title }}</a>
                        {% if algo.comment_set.count > 0 %}
                        <span class="text-danger small ml-2">[{{ algo.comment_set.count }}]</span>
                        {% endif %}
                    </td>
                    <td>{{ algo.author.userID }}</td>
                    <td>{{ algo.create_date }}</td>
                </tr>
                {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">게시물이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if algo_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ algo_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in algo_list.paginator.page_range %}
                {% if page_number >= algo_list.number|add:-5 and page_number <= algo_list.number|add:5 %}
                    {% if page_number == algo_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if algo_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ algo_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
        <a style="color: #fff;" class="btn btn-primary" 
        {% if user.is_authenticated %}
        href="{% url 'alit:algo_create' %}"
        {% else %}onclick="document.getElementById('id01').style.display='block'"
        {% endif %}>
        강의 등록하기</a>
    </div>
</div>

{% endblock %}

projects/alit/templates/alit/home.html
{% load static %}
<!doctype html>
<html lang="ko">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
        <!-- alit CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
        <title>A-lit</title>
        
        <meta content="width=device-width, initial-scale=1.0" name="viewport">
        <meta content="" name="keywords">
        <meta content="" name="description">

        <!-- Favicons -->
        <link href="img/favicon.png" rel="icon">
        <link href="img/apple-touch-icon.png" rel="apple-touch-icon">

        <!-- Bootstrap CSS File -->
        <link href="{% static '/lib/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet">

        <!-- Libraries CSS Files -->
        <link href="{% static '/lib/font-awesome/css/font-awesome.min.css'%}" rel="stylesheet">
        <link href="{% static '/lib/animate/animate.min.css'%}" rel="stylesheet">
        <link href="{% static '/lib/ionicons/css/ionicons.min.css'%}" rel="stylesheet">
        <link href="{% static '/lib/owlcarousel/assets/owl.carousel.min.css'%}" rel="stylesheet">
        <link href="{% static '/lib/lightbox/css/lightbox.min.css'%}" rel="stylesheet">

        <!-- Main Stylesheet File -->
        <link href="{% static 'style.css' %}" rel="stylesheet">

        <!-- =======================================================
            Theme Name: DevFolio
            Theme URL: https://bootstrapmade.com/devfolio-bootstrap-portfolio-html-template/
            Author: BootstrapMade.com
            License: https://bootstrapmade.com/license/
        ======================================================= -->

    </head>
    <body>
        {% include "navbar.html" %}
        
        {% block content %}
        {% endblock %}
        <!-- jQuery JS -->
        <script src="{% static 'jquery-3.5.1.min.js' %}"></script>
        <!-- Bootstrap JS -->
        <script src="{% static 'bootstrap.min.js' %}"></script>
    </body>
</html>

projects/alit/templates/alit/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ question.author.userID }}</div>
                    <div>{{ question.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2 text-left">
                    <div class="mb-2">{{ answer.author.userID }}</div>
                    <div>{{ answer.create_date }}</div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'alit:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
            {% if form.errors %}
                <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                    {% endif %}
                {% endfor %}
                </div>
            {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        {% if user.is_authenticated %}
        <input type="submit" value="답변등록" class="btn btn-primary">
        {% endif %}
        
    </form>
</div>
{% endblock %}

projects/alit/templates/alit/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}

        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{ form.subject.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

projects/alit/templates/alit/question_list.html
{% extends 'base.html' %}
{% load alit_filter %}
{% block content %}
 {% comment %} class="intro route bg-image" style="background-image: url({% static 'img/Rotterdam_street.jpg' %})" {% endcomment %}
<div>
    <div class="container my-3">
        <table class="table">
            <thead>
            <tr class="thead-dark text-center">
                <th>번호</th>
                <th style="width:50%">제목</th>
                <th>글쓴이</th>
                <th>작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if question_list %}
                {% for question in question_list %}
                <tr class="text-center">
                    <td>{{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}</td>
                    <td class="text-left">
                        <a href="{% url 'alit:questiondetail' question.id %}">{{ question.subject }}</a>
                        {% if question.answer_set.count > 0 %}
                        <span class="text-danger small ml-2">[{{ question.answer_set.count }}]</span>
                        {% endif %}
                    </td>
                    <td>{{ question.author.userID }}</td>
                    <td>{{ question.create_date }}</td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">질문이 없습니다.</td>
                </tr>
            {% endif %}
            </tbody>
        </table>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.previous_page_number }}">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in question_list.paginator.page_range %}
                {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                    {% if page_number == question_list.number %}
                    <li class="page-item active" aria-current="page">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{ page_number }}">{{ page_number }}</a>
                    </li>
                    {% endif %}
                {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ question_list.next_page_number }}">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
            </li>
            {% endif %}
        </ul>
        <!-- 페이징처리 끝 -->
        <a style="color: #fff;" class="btn btn-primary" 
        {% if user.is_authenticated %}
        href="{% url 'alit:question_create' %}"
        {% else %}onclick="document.getElementById('id01').style.display='block'"
        {% endif %}>
        질문 등록하기</a>
    </div>
</div>

{% endblock %}