projects/alit/alit/urls.py
from django.urls import path

from . import views

app_name = "alit"

urlpatterns = [
    path('', views.base, name='base'),
    
    path('questionlist/', views.Question_index, name='questionlist'),
    path('<int:question_id>/', views.Question_detail, name='questiondetail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),

    path('algolist/', views.Algoindex, name='algolist'),
    path('algo/<int:algo_id>/', views.Algodetail, name='algodetail'),
    path('algo/create/', views.algo_create, name='algo_create'),
    path('comment/create/algo/<int:algo_id>/', views.comment_create, name='comment_create'),

]

projects/alit/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='index.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),    
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    
]

projects/alit/config/urls.py
from django.contrib import admin
from django.urls import path, include
from alit import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('alit/', include('alit.urls')),
    path('common/', include('common.urls')),
    
]

projects/alit/common/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser

class UserManager(BaseUserManager):
    def create_user(self, userID, birth, name, password, email, belong):
        if not userID:
            raise ValueError('Users must have an userID')

        user = self.model(
            email=self.normalize_email(email),
            belong=belong,
            userID=userID,
            name=name,
            birth=birth,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, userID, name, birth, email, belong, password):
        user = self.create_user(
            email=email,
            password=password,
            belong=belong,
            userID=userID,
            name=name,
            birth=birth,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name='email',
        max_length=255,
        unique=True,
    )
    userID = models.CharField(
        max_length=255,
        unique=True,
    )
    belong = models.CharField(
        max_length=255,
    )
    birth = models.DateField()
    name = models.CharField(max_length=255, )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'userID'   # login 할 때 username에 쓰임
    REQUIRED_FIELDS = ['name', 'birth', 'email', 'belong']

    def __str__(self):
        return self.userID

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

projects/alit/common/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import User


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('name', 'birth', 'userID', 'email', 'belong')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('name', 'birth', 'userID', 'email', 'password', 'belong',
                  'is_active', 'is_admin')

    def clean_password(self):
        return self.initial["password"]

projects/alit/common/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserCreationForm
from django.http import HttpResponse, HttpResponseRedirect

def signup(request):
    """ 계정생성 """

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            id = form.cleaned_data.get('userID')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(userID=id, password=raw_password)
            login(request, user)
            return HttpResponseRedirect(request.POST['index'])
            # return redirect('alit:index')
    else:
        form = UserCreationForm()
    return render(request, 'common/signup.html', {'form': form})

def profile(request):
    """ 프로필 수정 """

projects/alit/templates/common/login.html
{% block content %}
<div id="id01" class="modal">
  
  <form class="modal-content animate" action="{% url 'common:login' %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="next" value="{{ next }}">
    {% include "form_errors.html" %}
    <div class="log-container">
      <label for="username"><b>ID</b></label>
      <input type="text" placeholder="Enter Username" name="username" id="username" 
      value="{{ form.username.value|default_if_none:'' }}">

      <label for="password"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="password" 
      value="{{ form.password.value|default_if_none:'' }}">
      
      <button type="submit">Login</button>
      <label>
        <input type="checkbox" checked="checked" name="remember"> Remember me
      </label>
      <span style="cursor: pointer; float: right;"><a href="{% url 'common:signup' %}">Create an account</a></span>
    </div>
  
    
    <div class="log-container" style="background-color:#f1f1f1">
      <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelbtn">Cancel</button>
      <span class="psw">Forgot <a href="{% url 'common:signup' %}">password?</a></span>
    </div>
  </form>
</div>
{% endblock  %}

projects/alit/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <div class="row my-3">
        <div class="col-4">
            <h4>계정생성</h4>
        </div>
        <div class="col-8 text-right">
            <span>또는 <a href="{% url 'common:login' %}">로그인 하세요.</a></span>
        </div>
    </div>
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="name">이름</label>
            <input type="text" class="form-control" name="name" id="name"
                   value="{{ form.name.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="birth">생년월일</label>
            <input type="date" class="form-control" name="birth" id="birth"
                   value="{{ form.birth.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="userID">아이디</label>
            <input type="text" class="form-control" name="userID" id="userID"
                   value="{{ form.userID.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="belong">학교/회사 또는 소속</label>
            <input type="text" class="form-control" name="belong" id="belong"
                   value="{{ form.belong.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="email">이메일</label>
            <input type="text" class="form-control" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}